trigger: 
- main
pool: 
  vmImage: 'ubuntu latest'

stages:
- stage: build
  jobs:
  - job: first job
    steps:
    - bash: echo this is first job
- stage: deploy
  dependsOn: first job
  jobs:
  - job: first job
    steps:
    - bash: echo this is second job
